# Stage 1: Build 
From mcr.microsoft.com/dptnet/sdk:10.0 AS Build
WORKDIR /src

#Copy csproj and restore dependencies
COPY ["TaskFlow.API.csproj", "./"]
RUN dotnet restore "TaskFlow.API.csproj"

#Copy everyting else and build
COPY . .
RUN dotnet publish "TaskFlow.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

# Stage 2: Runtimw
From mcr.microsoft.com/dptnet/aspnet:10.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

# Render exposes a dynamic PORT environment variable (default 8080)
ENV ASPNETCORE_URLS=http://+:8000
EXPOSE 8000

ENTRYPOINT ["dotnet", "TaskFlow.API.dll"]
